# melpa quality checks like checkdoc, byte-compile, package-lint for KIT.el
# using melpazoid: https://github.com/riscy/melpazoid

name: build KIT.el
on:
  push:
    branches:
      - 'master'
      - 'release/1.x'
    paths:
      - src/interface/emacs/*.el
      - .github/workflows/build_KIT_el.yml
  pull_request:
    branches:
      - 'master'
      - 'release/1.x'
    paths:
      - src/interface/emacs/*.el
      - .github/workflows/build_KIT_el.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with: { python-version: 3.11 }
    - name: ‚è¨Ô∏è Install Dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install emacs && emacs --version
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid
    - name: üå°Ô∏è Validate KIT.el
      env:
        # KIT recipe from https://github.com/melpa/melpa/pull/8321/files
        RECIPE: (KIT :fetcher github :repo "KIT-ai/KIT" :files ("src/interface/emacs/*.el"))
        EXIST_OK: true
        LOCAL_REPO: ${{ github.workspace }}
      run: echo $GITHUB_REF && make -C ~/melpazoid
